sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 10
before_install:
  - npm i -g npm@^3.0.0
  - sleep 1
before_script:
  - npm prune
script:
  - npm run build:travis
  - cd docs
  - npm install
  - npm run build
  - cd ..
after_success:
  - npm run semantic-release
  # - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
branches:
  only:
    - master
    - /^greenkeeper/.*$/
